
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA FUNCTION_SYMBOL LPAREN RPAREN VARIABLEterm : FUNCTION_SYMBOL LPAREN arg_list RPAREN\n                | VARIABLEarg_list : term COMMA arg_list\n                    | term'
    
_lr_action_items = {'RPAREN':([3,5,6,8,9,],[-2,-4,8,-1,-3,]),'COMMA':([3,5,8,],[-2,7,-1,]),'LPAREN':([2,],[4,]),'VARIABLE':([0,4,7,],[3,3,3,]),'FUNCTION_SYMBOL':([0,4,7,],[2,2,2,]),'$end':([1,3,8,],[0,-2,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'term':([0,4,7,],[1,5,5,]),'arg_list':([4,7,],[6,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> term","S'",1,None,None,None),
  ('term -> FUNCTION_SYMBOL LPAREN arg_list RPAREN','term',4,'p_term','term_parser.py',33),
  ('term -> VARIABLE','term',1,'p_term','term_parser.py',34),
  ('arg_list -> term COMMA arg_list','arg_list',3,'p_arg_list','term_parser.py',39),
  ('arg_list -> term','arg_list',1,'p_arg_list','term_parser.py',40),
]
